// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHJvw5Jvw6POEwVP3ys_2x_RzsArgI68',
    appId: '1:1074558085900:web:31fc176ef62079ad29b729',
    messagingSenderId: '1074558085900',
    projectId: 'vize-30719048-main',
    authDomain: 'vize-30719048-main.firebaseapp.com',
    storageBucket: 'vize-30719048-main.appspot.com',
    measurementId: 'G-QPWNP3J4MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACJp0WZOGbDC2CSL4W29RwxLi7s3ONGJs',
    appId: '1:1074558085900:android:a61d2a70080697ab29b729',
    messagingSenderId: '1074558085900',
    projectId: 'vize-30719048-main',
    storageBucket: 'vize-30719048-main.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCitfkUFbubohQ-Ryyozoh16tinYidKw6A',
    appId: '1:1074558085900:ios:84abdbca71e36f8729b729',
    messagingSenderId: '1074558085900',
    projectId: 'vize-30719048-main',
    storageBucket: 'vize-30719048-main.appspot.com',
    iosClientId: '1074558085900-dtdr57vdiaegn1mekkee1vj4bp8ur1gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCitfkUFbubohQ-Ryyozoh16tinYidKw6A',
    appId: '1:1074558085900:ios:84abdbca71e36f8729b729',
    messagingSenderId: '1074558085900',
    projectId: 'vize-30719048-main',
    storageBucket: 'vize-30719048-main.appspot.com',
    iosClientId: '1074558085900-dtdr57vdiaegn1mekkee1vj4bp8ur1gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
